CREATE TABLE IF NOT EXISTS weekly_stock_prices (
  date DATE PRIMARY KEY,
  open DOUBLE PRECISION,
  high DOUBLE PRECISION,
  low DOUBLE PRECISION,
  close DOUBLE PRECISION,
  volume DOUBLE PRECISION
);